var canvas = document.createElement('canvas');
canvas.id     = "mycanvas";
canvas.width  = 300;
canvas.height = 300;
canvas.style.zIndex   = 8;
canvas.style.position = "absolute";
canvas.style.border   = "1px solid";
document.body.appendChild(canvas);
var ctx = canvas.getContext("2d");
ctx.fillStyle = "#FF0000";
ctx.fillRect(0,0,150,75);
ctx.fillStyle = "#cc33ff";
for(var pos = 0;pos<200;pos+=5) ctx.fillRect(pos,pos,5,5);