// Generated by CoffeeScript 1.10.0
(function() {
  var f, getobj, match;

  getobj = function(len) {
    var x;
    return [
      (function() {
        var i, ref, results;
        results = [];
        for (x = i = 1, ref = len; 1 <= ref ? i <= ref : i >= ref; x = 1 <= ref ? ++i : --i) {
          results.push({});
        }
        return results;
      })()
    ];
  };

  f = {
    who: "do",
    dum: 5
  };

  match = function(input, patt) {
    return patt.test(input);
  };

}).call(this);

//# sourceMappingURL=states.js.map
